### PR TITLE
Release Candidate, 0.1.2

### PR DESCRIPTION
**Pull request by dopry**
- CI testing has been fixed
- API methods requiring subid have been fixed. 
- API returns empty object when result is an empty string to avoid parse errors with .json().

### CODE REVIEW

**Comment by dopry** [comment]
@aranhoide, hey wondering if you can pull master and give it a test? I'd like to have at least one external tester give it a go before pushing the release out to pip.

**Comment by aranhoide** [comment]
I'm in the middle of a long job; I'll do that first thing tomorrow.  That said, they used to not work whatsoever, so the change can only be for the better. :)

**Comment by dopry** [comment]
@aranhoide: I appreciate it. I'm going to add a few integration tests that depend on a VULTR_KEY environment variable. If you're feeling brave give them a shot. I should be online tomorrow 8a-6p EST (UTC-5), hit me up if you want any help reviewing. I was able to successfully create, list, reboot, and destroy servers.

**Comment by dopry** [comment]
@aranhoide: went ahead and merged so there would be a working version on pypi. give it a try. I'd really love to see getlantern in sync with this repo.

**Comment by dopry** [comment]
@cro, would love it if you could take a look as well.

**Pull request merged**
